load('r_objects/180308_PseudoGorsmyMonocle.rdata')
ls()
library(monocle)
gorsmy
plot_cell_trajectory(gorsmy,color_by="Res1.2") + facet_wrap(~isElfMouse,nrow=1)
plot_cell_trajectory(gorsmy,color_by="res.1.2") + facet_wrap(~isElfMouse,nrow=1)
plot_cell_trajectory(gorsmy,markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(isElfMouse~Phase) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
plot_cell_trajectory(gorsmy,markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
table(pData(gorsmy)$isElfMouse)
head(pData(gorsmy))
#cellkeep<-c(
ano<-pData(gorsmy)
cellkeep<-c(rownames(ano)[ano$isElfMouse=="Elf5"],sample(rownames(ano)[ano$isElfMouse=="WT",length(rownames(ano)[ano$isElfMouse=="Elf5"])])
)
cellkeep<-c(rownames(ano)[ano$isElfMouse=="Elf5"],sample(rownames(ano)[ano$isElfMouse=="WT",length(rownames(ano)[ano$isElfMouse=="Elf5"])])
length(rownames(ano)[ano$isElfMouse=="Elf5"])
cellkeep<-c(rownames(ano)[ano$isElfMouse=="Elf5"],sample(rownames(ano)[ano$isElfMouse=="WT"],length(rownames(ano)[ano$isElfMouse=="Elf5"])])
cellkeep<-c(rownames(ano)[ano$isElfMouse=="Elf5"],sample(rownames(ano)[ano$isElfMouse=="WT"],length(rownames(ano)[ano$isElfMouse=="Elf5"])
)
)
cellkeep
plot_cell_trajectory(gorsmy[cellkeep,],markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
plot_cell_trajectory(gorsmy[,cellkeep],markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
head(colnames(gorsmy))
table(cellkeep %in% colnames(gorsmy))
table(colnames(gorsmy) %in% cellkeep)
x<-gorsmy[,celleep]
x<-gorsmy[,cellkeep]
plot_cell_trajectory(x,markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
plot_cell_trajectory(x)
dim(pData(x)
)
dim(pData(x))
dim(pData(f))
dim(fData(x))
head(fData(x))
dim(gorsmy)
dim(x)
str(x)
plot_cell_trajectory(x)
HSMM
load('r_objects/180209_monocleObjs.rdata')
HSSM<-HSSM[,cellkeep]
HSMM<-HSSM[,cellkeep]
load("r_objects/180209_monocleObjs.rdata")
HSSM
HSMM
HSMM<-HSSM[,cellkeep]
HSMM<-HSMM[,cellkeep]
gorsmy_downSampleByGenotype<-plotTraj(HSMM,gorsmy_markers,"180308_gorsmy_lineage",c("res.2","Phase"))
plotTraj<-function(monoclObj,genevec,filename,metadataDesired,...){
message('depending on your gene list, this might take ages \n you have been warned')
pdf(file=paste0("plots/",filename,".pdf"))
tmp<-monoclObj
tmp <- setOrderingFilter(tmp, genevec)
#print(plot_ordering_genes(tmp))
ncenters <- length(unlist(sapply(metadataDesired, function(x) unique( as(phenoData(HSMM),'data.frame')[,x]))))
tmp <- reduceDimension(tmp, max_components=2,method = 'DDRTree')#,auto_param_selection = F, nCenter = ncenters)
tmp <- orderCells(tmp, reverse=FALSE)
sapply(c(metadataDesired,"Pseudotime"), function(x) print(plot_cell_trajectory(tmp, color_by=x)))
return(tmp)
dev.off()
}
gorsmy_downSampleByGenotype<-plotTraj(HSMM,gorsmy_markers,"180308_gorsmy_lineage",c("res.2","Phase"))
dev.off()
dev.off()
gorsmy_downSampleByGenotype<-plotTraj(HSMM,gorsmy_markers,"180612_downSampled_gorsmy_lineage",c("res.2","Phase"))
save(gorsmy,file="r_objects/180612_PseudoGorsmyMonocle.rdata")
plot_cell_trajectory(gorsmy_downSampleByGenotype<-plotTraj,markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
plot_cell_trajectory(gorsmy_downSampleByGenotype,markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
plot_cell_trajectory(gorsmy_downSampleByGenotype,markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
gorsmy_downSampleByGenotype
load("r_objects/180612_PseudoGorsmyMonocle.rdata")
plot_cell_trajectory(gorsmy_downSampleByGenotype,markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
gorsmy_downSampleByGenotype <-plotTraj(HSMM,gorsmy_markers,"180612_downSampled_gorsmy_lineage",c("res.2","Phase"))
save(gorsmy_downSampleByGenotype,file="r_objects/180612_PseudoGorsmyMonocle.rdata")
plot_cell_trajectory(gorsmy_downSampleByGenotype,markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
dev.off()
dev.off()
dev.off()
plot_cell_trajectory(gorsmy_downSampleByGenotype,markers="Elf5",markers_linear=T,color_by="res.1.2") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
plot_cell_trajectory(gorsmy_downSampleByGenotype,markers="Elf5",markers_linear=T,color_by="State") + facet_grid(~isElfMouse) + ggtitle("SmythMarkerTrajectories, colour by  cluster, point size by Elf5, split by genotype")
dim(pData(gorsmy_downSampleByGenotype)$isElf)
table(pData(gorsmy_downSampleByGenotype)$isElf)
gorsmy
table(pData(gorsmy)$isElf)
str(gorsmy)
str(gorsmy[,cellkeep)
str(gorsmy[,cellkeep])
head(gorsmy@reducedDims)
str\(gorsmy@reducedDims)
str(gorsmy@reducedDims)
str(gorsmy@reducedDim)
str(gorsmy@reducedDims)
??subset
reducedDimA(gorsmy)
reducedDim(gorsmy)
reducedDims(gorsmy)
reducedDimensions(gorsmy)
reduceDimensions(gorsmy)
reduceDimension(gorsmy)
plot_cell_trajectory(gorsmy[,cellkeep],markers="Elf5",markers_linear=T,color_by="res.1.2")
str(gorsmy[,cellkeep])
str(gorsmy)
sink('subset.txt')
str(gorsmy[,cellkeep])
sink()
sink('parent.txt')
str(gorsmy)
sink()
reducedDimS(gorsmy)
y<-reducedDimS(gorsmy)
plot(y)
plot(t(y))
y<-t(reducedDimS(gorsmy))
head(y)
y<-y[cellkeep,]
reducedDimS(gorsmy)<-t(y)
elf<-gorsmy['Elf5',]
head(elf)
head(elf@data)
head(exprs(elf))
head(as.data.frame(t(exprs(elf)))
)
head(as.data.matrix(t(exprs(elf)))
)
head(data.matrix(t(exprs(elf)))
)
elf<-data.matrix(t(exprs(elf)))
dim(elf)
dim(y)
pd<-pData(gorsmy)$isElfMouse)
pd<-pData(gorsmy)$isElfMouse
head(pd_
head(pd)
pd<-as(pData(gorsmy),'data.frame')
head(pd)
$pd$x=y[rownames(pd),
head(y)
pd$x=y[rownames(pd),1]
dim(y)
dim(pd)
pd<-pd[cellkeep,]
pd$x=y[rownames(pd),1]
pd$y=y[rownames(pd),2]
pd$elf=elf[rownames(pd),1]
head(pd)
table(pd$isElfMouse)
ggplot(pd,aes(x=x,y=y,col=res.1.2)) + geom_point() + facet_wrap(~isElfMouse)
str(pd)
ggplot(pd,aes(x=x,y=y,col=as.numeric(as.character(res.1.2)))) + geom_point() + facet_wrap(~isElfMouse)
ggplot(pd,aes(x=x,y=y,col=as.integer(as.character(res.1.2)))) + geom_point() + facet_wrap(~isElfMouse)
ggplot(pd,aes(x=x,y=y,col=as.character(res.1.2))) + geom_point() + facet_wrap(~isElfMouse)
ggplot(pd,aes(x=x,y=y,col=factor(as.numeric(res.1.2)))) + geom_point() + facet_wrap(~isElfMouse)
ggplot(pd,aes(x=x,y=y,col=factor(as.numeric(res.1.2)))) + geom_point(size=Elf5) + facet_wrap(~isElfMouse)
ggplot(pd,aes(x=x,y=y,col=factor(as.numeric(res.1.2)))) + geom_point(size=elf) + facet_wrap(~isElfMouse)
ggplot(pd,aes(x=x,y=y,col=factor(as.numeric(res.1.2)))) + geom_point(size=elf+.1) + facet_wrap(~isElfMouse)
ggplot(pd,aes(x=x,y=y,col=factor(as.numeric(res.1.2)))) + geom_point(cex=elf+.1) + facet_wrap(~isElfMouse)
args(geom_point)
ggplot(pd,aes(x=x,y=y,col=factor(as.numeric(res.1.2)))) + geom_point(cex=elf+.1) + facet_wrap(~isElfMouse)
ggplot(pd,aes(x=x,y=y,col=factor(as.numeric(res.1.2)))) + geom_point() + facet_wrap(~isElfMouse)
ggsave("plots/180612_subsetted_gorsmy_trajectories.pdf")
ppd<-as(pData(gorsmy),'data,frame')
ppd<-as(pData(gorsmy),'data.frame')
head(ppd)
table(ppd$res.1.2,ppd$State)
x<-table(ppd$res.1.2,ppd$State)
x
x<-data.matrix(table(ppd$res.1.2,ppd$State))
x
x<-data.frame(x)
x
head(c)
head(s)
head(sx
head(x)
x<-data.matrix(table(ppd$isElfMouse,ppd$State))
x<-data.frame(data.matrix(table(ppd$isElfMouse,ppd$State)))
x
ggplot(ppd,aes(x=res.1.2)) + geom_bar()
ggplot(ppd,aes(x=State,col=res.1.2)) + geom_bar() + facet_wrap(isElfMouse
()
ggplot(ppd,aes(x=State,col=res.1.2)) + geom_bar() + facet_wrap(~isElfMouse)
ggplot(ppd,aes(x=State,fill=res.1.2)) + geom_bar(position='dodge') + facet_wrap(~isElfMouse)
ggplot(ppd,aes(x=as.numeric(res.1.2),fill=State)) + geom_bar(position='dodge') + facet_wrap(~isElfMouse)
ggplot(ppd,aes(x=as.numeric(res.1.2),fill=State)) + geom_bar() + facet_wrap(~isElfMouse)
ggplot(ppd,aes(x=as.numeric(res.1.2),fill=State)) + geom_bar(position='identity') + facet_wrap(~isElfMouse)
ggplot(ppd,aes(x=as.numeric(res.1.2),fill=State)) + geom_bar(position='fill') + facet_wrap(~isElfMouse)
ggsave("plots/180612_normalised_gorsmy_res1.2vsState.pdf")
x11() ; ggplot(ppd,aes(x=as.numeric(res.1.2),fill=State)) + geom_bar() + facet_wrap(~isElfMouse)
quartz() ; ggplot(ppd,aes(x=as.numeric(res.1.2),fill=State)) + geom_bar() + facet_wrap(~isElfMouse)
savehistory(file="180612_monocle_downsampleplotAndNormalisedBarplots.r")
